basePath: /
definitions:
  dto.V1CreateOrderRequest:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1Order'
        type: array
    type: object
  dto.V1CreateOrderResponse:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1Order'
        type: array
    type: object
  dto.V1Order:
    properties:
      createdAt:
        type: string
      customerId:
        type: integer
      deliveryAddress:
        type: string
      id:
        type: integer
      orderItems:
        items:
          $ref: '#/definitions/dto.V1OrderItem'
        type: array
      totalPriceCents:
        type: integer
      totalPriceCurrency:
        type: string
      updatedAt:
        type: string
    type: object
  dto.V1OrderItem:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      orderId:
        type: integer
      priceCents:
        type: integer
      priceCurrency:
        type: string
      productId:
        type: integer
      productTitle:
        type: string
      productUrl:
        type: string
      quantity:
        type: integer
      updatedAt:
        type: string
    type: object
  dto.V1QueryOrdersRequest:
    properties:
      customerIds:
        items:
          type: integer
        type: array
      ids:
        items:
          type: integer
        type: array
      includeOrderItems:
        type: boolean
      page:
        type: integer
      pageSize:
        type: integer
    type: object
  dto.V1QueryOrdersResponse:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1Order'
        type: array
    type: object
host: localhost:5000
info:
  contact: {}
  description: API for managing orders
  title: Order Service API
  version: "1.0"
paths:
  /api/v1/order/batch-create:
    post:
      consumes:
      - application/json
      description: Creates orders with order items
      parameters:
      - description: Create Order Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.V1CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.V1CreateOrderResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create orders batch
      tags:
      - orders
  /api/v1/order/query:
    post:
      consumes:
      - application/json
      description: Returns orders with optional order items
      parameters:
      - description: Query Orders Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.V1QueryOrdersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.V1QueryOrdersResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Query orders
      tags:
      - orders
swagger: "2.0"
