basePath: /
definitions:
  dto.V1CreateAuditLogOrderRequest:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1LogOrder'
        type: array
    type: object
  dto.V1CreateAuditLogOrderResponse:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1LogOrder'
        type: array
    type: object
  dto.V1CreateOrderRequest:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1Order'
        type: array
    type: object
  dto.V1CreateOrderResponse:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1Order'
        type: array
    type: object
  dto.V1LogOrder:
    properties:
      created_at:
        type: string
      customer_id:
        type: integer
      id:
        type: integer
      order_id:
        type: integer
      order_item_id:
        type: integer
      order_status:
        type: string
      updated_at:
        type: string
    type: object
  dto.V1Order:
    properties:
      created_at:
        type: string
      customer_id:
        type: integer
      delivery_address:
        type: string
      id:
        type: integer
      order_items:
        items:
          $ref: '#/definitions/dto.V1OrderItem'
        type: array
      total_price_cents:
        type: integer
      total_price_currency:
        type: string
      updated_at:
        type: string
    type: object
  dto.V1OrderItem:
    properties:
      created_at:
        type: string
      id:
        type: integer
      order_id:
        type: integer
      price_cents:
        type: integer
      price_currency:
        type: string
      product_id:
        type: integer
      product_title:
        type: string
      product_url:
        type: string
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  dto.V1QueryOrdersRequest:
    properties:
      customer_ids:
        items:
          type: integer
        type: array
      ids:
        items:
          type: integer
        type: array
      include_order_items:
        type: boolean
      page:
        type: integer
      page_size:
        type: integer
    type: object
  dto.V1QueryOrdersResponse:
    properties:
      orders:
        items:
          $ref: '#/definitions/dto.V1Order'
        type: array
    type: object
host: localhost:5000
info:
  contact: {}
  description: API for managing orders
  title: Order Service API
  version: "1.0"
paths:
  /api/v1/audit-log/order/batch-create:
    post:
      consumes:
      - application/json
      description: Creates audit logs for orders
      parameters:
      - description: Create Audit Log Order Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.V1CreateAuditLogOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.V1CreateAuditLogOrderResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create audit logs for orders batch
      tags:
      - audit_logs
  /api/v1/order/batch-create:
    post:
      consumes:
      - application/json
      description: Creates orders with order items
      parameters:
      - description: Create Order Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.V1CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.V1CreateOrderResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create orders batch
      tags:
      - orders
  /api/v1/order/query:
    post:
      consumes:
      - application/json
      description: Returns orders with optional order items
      parameters:
      - description: Query Orders Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.V1QueryOrdersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.V1QueryOrdersResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Query orders
      tags:
      - orders
swagger: "2.0"
